apiVersion: v1
data:
  OS_PASSWORD: RHAtMjAyNSFUcmFjZSNBMSRNb3Jl
  OS_USERNAME: ZGF0YXByZXBwZXI=
kind: Secret
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
  name: dp-os-auth
  namespace: logging
type: Opaque
