apiVersion: v1
kind: ConfigMap
metadata:
  annotations:
    argocd.argoproj.io/tracking-id: true-trace-fluentd:/ConfigMap:logging/fluentd-config-true-trace-fluentd
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":null,"kind":"ConfigMap","metadata":{"annotations":{"argocd.argoproj.io/tracking-id":"true-trace-fluentd:/ConfigMap:logging/fluentd-config-true-trace-fluentd"},"labels":{"app.kubernetes.io/instance":"true-trace-fluentd","app.kubernetes.io/managed-by":"Helm","app.kubernetes.io/name":"true-trace-fluentd","app.kubernetes.io/version":"img.1.0.5","helm.sh/chart":"true-trace-fluentd-1.0.5-pps"},"name":"fluentd-config-true-trace-fluentd","namespace":"logging"}}
  labels:
    app.kubernetes.io/instance: true-trace-fluentd
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: true-trace-fluentd
    app.kubernetes.io/version: img.1.0.5
    helm.sh/chart: true-trace-fluentd-1.0.5-pps
  name: fluentd-config-true-trace-fluentd
  namespace: logging
