apiVersion: v1
data:
  ca.crt: |
    -----BEGIN CERTIFICATE-----
    MIIELTCCApWgAwIBAgIRAOpH2HF8hAkb9IUOoeTGfFwwDQYJKoZIhvcNAQELBQAw
    LzEtMCsGA1UEAxMkM2JkMTkzZWEtMmJiNy00MTI2LTliNTItZTliMTU5MWQxZjVk
    MCAXDTI1MDUxOTA3NDE1MFoYDzIwNTUwNTEyMDg0MTUwWjAvMS0wKwYDVQQDEyQz
    YmQxOTNlYS0yYmI3LTQxMjYtOWI1Mi1lOWIxNTkxZDFmNWQwggGiMA0GCSqGSIb3
    DQEBAQUAA4IBjwAwggGKAoIBgQC4oiazVKs4ftcGTHiZCubZY/ql/QD0lKnt/sVE
    DAlpW9/uYh2xwToLbIwSwjt7DOY7vwsSlLdVjthkSbhZCaXuCjCSbO07ZBcPbM4/
    zW96bM4tjs8UCVVawQh46FERkpDvPTsUVMNDgf6j/ttA9c6LSLilP4kMuffldsI6
    kx+XxYsJcWb0SizkGQWy5q2IPnJDTy1jVjj7bqBR4VmUiuX7egZ3odv5ba7EvWuP
    +tmdqHnNXb2nw9JUKEjgtOx+2u/JJs0JWFlQ0eCb3X+B5TsXPvsXmHTUpmU0KWq6
    oH8Vnpjbj9CLmk+bbo6GuM4oYHT8JBik1v2UqSnYlGo2zMQj9ulOT13LpjUCghX3
    8hfayWiwpKcsA0N4ludyLXPSuSuDHvTANOGPeGTe4E1SXjUR7wmE66PeaP2GT7Z6
    DabU1gVf7vHlLcQId4Gzmi0BopA3LDqAwhos/cz7DeR59/6+O4fUg3Sb6dl6lJNA
    l1HR72zO/TpfEFZYXRGIz6YkYN0CAwEAAaNCMEAwDgYDVR0PAQH/BAQDAgIEMA8G
    A1UdEwEB/wQFMAMBAf8wHQYDVR0OBBYEFLWg0QcmqpQ91F82WZtnSn0LEd8aMA0G
    CSqGSIb3DQEBCwUAA4IBgQAQaT3w4QH9IvzqSfnCxzYOOJb7TgcLCrsKtJNs/qVe
    Zal8n5JVuF9R21JQiCzn6ixcEFTj5App7bEgUExcLtp2xmOlLDvqjKXCkmApkTOe
    vSeNOs9cp4gxxuJmbDSuqE92MW36vRxwL7kecRoVUJIBPIRQV0Os7oN8mpWnbHrk
    7abeVOhjlqa6N5X7FLt7R1anuHn2s7uPzS0v2GXcdr2wUZGLc21pVrVmNc8N/hFY
    mPdyhhkI76gPxc5Arioj898XN6wJ0bOaw42yHbrZRbRkdcsWu3+ofL7H7pnoahNF
    bBH74ln1JrQO34ANF7BVXgL56yc6DX7tkauP5IgznFvCp4LbYd2osv4pAdQ7qLnk
    SSdUCpB+uK1QwGOZD3IR1DkQ7uCJT5Vb8hobeiVCOpCe68IEyCDEmlKUydGKo+j8
    F9fGP/oUJ7nM/nd9blUXZTnq6dX3xQnohWJ2v89UM/QEcVomjhloWtXu9kA+fwl6
    jUJMCEQ2xiGmods0swr4Pfs=
    -----END CERTIFICATE-----
kind: ConfigMap
metadata:
  annotations:
    kubernetes.io/description: Contains a CA bundle that can be used to verify the
      kube-apiserver when using internal endpoints such as the internal service IP
      or kubernetes.default.svc. No other usage is guaranteed across distributions
      of Kubernetes clusters.
  name: kube-root-ca.crt
  namespace: logging
