apiVersion: v1
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":null,"kind":"ConfigMap","metadata":{"annotations":{},"labels":{"app.kubernetes.io/instance":"true-trace-fluentd","app.kubernetes.io/managed-by":"Helm","app.kubernetes.io/name":"true-trace-fluentd","app.kubernetes.io/version":"img.1.0.7","helm.sh/chart":"true-trace-fluentd-1.0.7-pps"},"name":"fluentd-config-true-trace-fluentd","namespace":"logging"}}
  creationTimestamp: "2026-01-09T09:28:42Z"
  labels:
    app.kubernetes.io/instance: true-trace-fluentd
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: true-trace-fluentd
    app.kubernetes.io/version: img.1.0.7
    helm.sh/chart: true-trace-fluentd-1.0.7-pps
  name: fluentd-config-true-trace-fluentd
  namespace: logging
  resourceVersion: "1770635437786159012"
  uid: de3c04d3-d3e8-4d9c-b0ad-fe1cc82c4bcf
