apiVersion: v1
kind: ConfigMap
metadata:
  name: true-trace-telemetry
  namespace: logging
  annotations:
    argocd.argoproj.io/tracking-id: true-trace-telemetry:/ConfigMap:logging/true-trace-telemetry
data:
  relay: |
    exporters:
      logging:
        loglevel: debug

      otlp/data-prepper-traces:
        endpoint: true-trace-prepper:21890
        tls:
          insecure: true

      otlp/data-prepper-metrics:
        endpoint: true-trace-prepper:21891
        tls:
          insecure: true

      otlp/data-prepper-logs:
        endpoint: true-trace-prepper:21892
        tls:
          insecure: true

    extensions:
      health_check: null

    processors:
      batch: null
      memory_limiter:
        check_interval: 5s
        limit_mib: 409
        spike_limit_mib: 128

    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            cors:
              allowed_headers:
                - '*'
              allowed_origins:
                - '*'
              max_age: 7200
            endpoint: 0.0.0.0:4318

    service:
      extensions:
        - health_check

      pipelines:
        traces:
          receivers:
            - otlp
          processors:
            - batch
          exporters:
            - otlp/data-prepper-traces

        metrics:
          receivers:
            - otlp
          processors:
            - batch
          exporters:
            - otlp/data-prepper-metrics

        logs:
          receivers:
            - otlp
          processors:
            - batch
          exporters:
            - otlp/data-prepper-logs

      telemetry:
        logs:
          error_output_paths:
            - stdout
          level: debug
          output_paths:
            - stdout

